services:
  tfstudio-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tfstudio
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    networks:
      - proxy

networks:
  proxy:
    external: true
