// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojwuhbzkjbkutpjnddpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qd3VoYnpramJrdXRwam5kZHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMjg3NTIsImV4cCI6MjA3NDcwNDc1Mn0.AefKWcQKD95QgVJqBXiu0I_HvDnAn-_fp7qP-SRsM3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});